return vim.g.vscode and {}
  or {
    require 'plugins.colorschemes.ashen',
    require 'plugins.colorschemes.ayu',
    require 'plugins.colorschemes.catppuccin',
    require 'plugins.colorschemes.cyberdream',
    require 'plugins.colorschemes.github',
    require 'plugins.colorschemes.gruvbox',
    require 'plugins.colorschemes.islands',
    require 'plugins.colorschemes.kanagawa',
    require 'plugins.colorschemes.nordic',
    require 'plugins.colorschemes.onedark',
    require 'plugins.colorschemes.oxocarbon',
    require 'plugins.colorschemes.poimandres',
    require 'plugins.colorschemes.rose-pine',
    require 'plugins.colorschemes.srcery',
    require 'plugins.colorschemes.techbase',
    require 'plugins.colorschemes.tokyonight',
    require 'plugins.colorschemes.vague',
    require 'plugins.colorschemes.vscode',
    require 'plugins.colorschemes.xcode',
  }
