return {
  'saghen/blink.cmp',
  dependencies = 'rafamadriz/friendly-snippets',
  version = 'v0.*',
  event = 'InsertEnter',
  opts = {
    keymap = {
      ['<C-space>'] = { 'show', 'show_documentation', 'hide_documentation' },
      ['<C-e>'] = { 'hide', 'fallback' },
      ['<CR>'] = { 'accept', 'fallback' },
      ['<C-n>'] = { 'snippet_forward', 'fallback' },
      ['<C-p>'] = { 'snippet_backward', 'fallback' },
      ['<S-Tab>'] = { 'select_prev', 'fallback' },
      ['<Tab>'] = { 'select_next', 'fallback' },
      ['<Up>'] = { 'select_prev', 'fallback' },
      ['<Down>'] = { 'select_next', 'fallback' },
      ['<C-b>'] = { 'scroll_documentation_up', 'fallback' },
      ['<C-f>'] = { 'scroll_documentation_down', 'fallback' },
    },
    appearance = {
      nerd_font_variant = 'mono',
      kind_icons = {
        Array = '',
        Boolean = '󰨙',
        Class = '',
        Codeium = '󰘦',
        Color = '󱓻',
        Control = '',
        Collapsed = '',
        Constant = '󰏿',
        Constructor = '',
        Copilot = '',
        Enum = '',
        EnumMember = '',
        Event = '',
        Field = '',
        File = '',
        Folder = '',
        Function = '󰊕',
        Interface = '',
        Key = '',
        Keyword = '',
        Method = '󰊕',
        Module = '',
        Namespace = '󰦮',
        Null = '',
        Number = '󰎠',
        Object = '',
        Operator = '',
        Package = '',
        Property = '',
        Reference = '',
        Snippet = '',
        String = '',
        Struct = '󰆼',
        Supermaven = '',
        TabNine = '󰏚',
        Text = '',
        TypeParameter = '',
        Unit = '',
        Value = '',
        Variable = '󰀫',
      },
    },
    completion = {
      accept = {
        auto_brackets = {
          enabled = true,
        },
      },
      menu = {
        draw = {
          treesitter = { 'lsp' },
        },
      },
      documentation = {
        auto_show = true,
        auto_show_delay_ms = 200,
      },
      -- list = {
      --   selection = 'manual',
      -- },
      trigger = {
        show_on_insert_on_trigger_character = false,
      },
    },
    sources = {
      providers = {
        lazydev = {
          name = 'LazyDev',
          module = 'lazydev.integrations.blink',
        },
      },
      default = { 'lsp', 'path', 'snippets', 'buffer', 'lazydev' },
      cmdline = {},
    },
  },
  opts_extend = { 'sources.default' },
}
