return {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    main = 'nvim-treesitter.configs',
    lazy = vim.fn.argc(-1) == 0, -- load treesitter early when opening a file from the cmdline
    -- dependencies = {
    --   "windwp/nvim-ts-autotag",
    --   "nvim-treesitter/nvim-treesitter-textobjects",
    --   "JoosepAlviste/nvim-ts-context-commentstring",
    -- },
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "diff",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "printf",
        "python",
        "query",
        "regex",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
      auto_install = false,
      highlight = {
        enable = true,
        -- additional_vim_regex_highlighting = { 'ruby' },
      },
      indent = { enable = true },
    },
  }
