return {
  'folke/which-key.nvim',
  enabled = true,
  event = 'VeryLazy',
  keys = {
    {
      '<leader>?',
      function() require('which-key').show { global = false } end,
      desc = 'Local Keymaps (which-key)',
    },
  },
  opts = {
    spec = {
      { '<leader>K', icon = { icon = '', color = 'grey' } },
      { '<leader>M', icon = { icon = '', color = 'purple' } },
      { '<leader>N', icon = { icon = '󰎕', color = 'green' } },
      { '<leader>s', icon = { icon = '󰆓', color = 'green' } },
      { '<leader>y', icon = { icon = '󰆏', color = 'green' } },
      { '<leader>/', icon = { icon = '󰦨', color = 'grey' } },
      { '<leader>?', icon = { icon = '', color = 'grey' } },
      { '<leader>\\', icon = { icon = '', color = 'purple' } },
      { '<leader>|', icon = { icon = '', color = 'purple' } },
      { '<leader><leader>', icon = { icon = '󱊔', color = 'green' } },
      { '<leader>c', group = 'code', mode = { 'n', 'x' } },
      { '<leader>cd', icon = { icon = '󰙅', color = 'orange' } },
      { '<leader>cf', icon = { icon = '󰉺', color = 'green' } },
      { '<leader>cr', icon = { icon = '', color = 'blue' } },
      { '<leader>cR', icon = { icon = '', color = 'green' } },
      { '<leader>cf', icon = { icon = '󰙅', color = 'orange' } },
      { '<leader>cW', icon = { icon = '', color = 'blue' } },
      { '<leader>d', group = 'debug', mode = { 'n', 'v' } },
      { '<leader>f', group = 'find' },
      { '<leader>fe', icon = { icon = '󰙅', color = 'purple' } },
      { '<leader>fH', icon = { icon = '󰋖', color = 'grey' } },
      { '<leader>f?', icon = { icon = '', color = 'grey' } },
      { '<leader>g', group = 'git', mode = { 'n', 'v' } },
      { '<leader>m', group = 'messages', icon = { icon = '󰍡', color = 'purple' } },
      { '<leader>mh', icon = { icon = '󰍡', color = 'purple' } },
      { '<leader>q', group = 'quickfix/diagnostics' },
      { '<leader>t', group = 'toggle' },
      { '<leader>tB', icon = { icon = '󰊢', color = 'orange' } },
      { '<leader>tD', icon = { icon = '󰊢', color = 'red' } },
      { '<leader>tm', icon = { icon = '', color = 'purple' } },
      { '<leader>tt', icon = { icon = '', color = 'red' } },
      { '<leader>,', group = 'settings', icon = { icon = '󰒓', color = 'grey' } },
      { '<leader>,m', icon = { icon = '󱌢', color = 'orange' } },
      { '<leader>,M', icon = { icon = '󱌢', color = 'orange' } },
      { '<leader>,t', icon = { icon = '󰔱', color = 'green' } },
      { '<leader>,T', icon = { icon = '󰔱', color = 'green' } },
    },
  },
}
